learning_template/basicapp/urls.py
from django.urls import path
from basicapp import views

app_name = 'basicapp'

urlpatterns = [
    path('relative/', views.relative, name='relative'),
    path('other/', views.other, name='other'),
]

learning_template/learning_template/urls.py
from django.contrib import admin
from django.urls import include, path
from basicapp import views

urlpatterns = [
    path('', views.index, name='index'),
    path('admin/', admin.site.urls),
    path('basicapp/', include('basicapp.urls'))
]

learning_template/basicapp/models.py
from django.db import models

# Create your models here.

learning_template/basicapp/views.py
from django.shortcuts import render

# Create your views here.

def index(request):
    context_dict = {'text':'hello wordl','number':100}
    return render(request, 'basicapp/index.html',context_dict)

def other(request):
    return render(request, 'basicapp/other.html')

def relative(request):
    return render(request, 'basicapp/relative_url_templates.html')

learning_template/templates/basicapp/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
  </head>
  <body>
    <nav class="navbar navbar-dark bg-dark">
      <div class="container">
        <ul class="nav">
          <li class="nav-item active"><a class="navbar-brand" href="{% url 'index'%}">BRAND</a></li>
          <li class="nav-item active"><a class="nav-link" href="{% url 'admin:index'%}">ADMIN</a></li>
          <li class="nav-item active"><a class="nav-link" href="{% url 'basicapp:other'%}">OTHER</a></li>
        </ul>
      </div>
     </nav>
     <div class="container">
       <!-- <div class="jumbotron"> -->
         {%block body_block %}
         {% endblock %}
       </div>
     </div>
  </body>
</html>

learning_template/templates/basicapp/index.html
<!DOCTYPE html>
{% extends "basicapp/base.html" %}
  {% block body_block%}
    <h1>WELCOME TO THE HOME PAGE</h1>
    <h1>This is index,html page showing</h1>
    <h1>{{ text|cut:'hello'}}</h1>
    <h1>{{ number|add:"99" }}</h1>
    {% endblock %}

learning_template/templates/basicapp/other.html
<!DOCTYPE html>
{% extends "basicapp/base.html" %}
  {%block body_block %}

    <h1>WELCOME TO OTHER</h1>
    <h2>This is an example of template inheritance</h2>
    {% endblock %}

learning_template/templates/basicapp/relative_url_template.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>

  </body>
</html>